# Generated by Django 6.0.2 on 2026-04-03 23:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='fantasy', max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('globalRating', models.FloatField(default=1.0)),
                ('cover', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
                ('summary', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField(max_length=500)),
                ('readingStatus', models.CharField(choices=[('u', 'Unread'), ('tr', 'To Read'), ('ip', 'In Progress'), ('r', 'Read')], default='u', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookSystem.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
