# Generated by Django 6.0.2 on 2026-04-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSystem', '0002_book_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrating',
            name='readingStatus',
            field=models.CharField(choices=[('u', 'Unread'), ('tr', 'To Read'), ('ip', 'Reading'), ('r', 'Read')], default='u', max_length=2),
        ),
    ]
