# Generated by Django 6.0.2 on 2026-04-05 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSystem', '0003_alter_userbookrating_readingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrating',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
